### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by ajtucker** [gitbucket/gitbucket-h2-backup-plugin#15]
Hi,

Thanks for making this plugin.  I've managed to get it working along with the backup script mentioned in the gitbucket wiki, albeit with a minor mod to pick up the file path in the HTTP response.

Next up is figuring out how to restore to a pristine installation of gitbucket from the backups.  For the database, I assume I just need to unzip the backup and put the resulting data.mv.db file in the right place?

Cheers!
Alex.

**Comment by McFoggy** [comment]
> albeit with a minor mod to pick up the file path in the HTTP response.

wasn't the already [provided response](https://github.com/gitbucket-plugins/gitbucket-h2-backup-plugin/blob/master/src/main/scala/fr/brouillard/gitbucket/h2/controller/H2BackupController.scala#L47) enough?
What did you do more?

> I assume I just need to unzip the backup and put the resulting data.mv.db file in the right place?

correct

**Comment by ajtucker** [comment]
The HTTP response is fine, it was the gitbucket example [backup.sh script](https://github.com/gitbucket/gitbucket/wiki/Backup#backup-script) that needed a tweak to take the response into account:

```
    echo "Database backup"
    RESP=$(curl -s $GITBUCKET_DB_BACKUP_URL)
    BACKUP_FILE=${RESP:6} # response is like "done: gitbucket-database-backup-YYYY-MM-DD-HHMM.zip"
    cp -f $GITBUCKET_DATA/$BACKUP_FILE $BACKUP_FOLDER > /dev/null

```
