### ISSUE TITLE
Plugin version is 1.3.0, but database version is 1.0

### ISSUE THREAD

**Issue by gedOHub** [gitbucket/gitbucket-h2-backup-plugin#18]
Hello,
I'm unable to initialize plugin. Error:

> SEVERE: Error during plugin initialization: /home/gitbucket/.gitbucket/plugins/gitbucket-h2-backup.jar
> java.lang.IllegalStateException: Plugin version is 1.3.0, but database version is 1.0

How this can be fixed?
Running GitBucket 4.4.0 with H2 Backup Plugin 1.3.0

**Comment by McFoggy** [comment]
Something failed during your update. Can you please try to manually correct your database using instructions in #16.

**Comment by gedOHub** [comment]
I don't have versions table
![No VERSION table](https://s12.postimg.org/or79gwojh/Screenshot_from_2016_10_04_14_36_11.png)

Logged in with user sa and no password. If I try with password it returns error of wrong username or password

**Comment by McFoggy** [comment]
To connect to the H2 db you should use the jdbc URL configured in system settings

![image](https://cloud.githubusercontent.com/assets/1119660/19075981/5a442f64-8a47-11e6-9fef-125417cb34c4.png)

In your screenshot you're connected to an empty DB. Once you hjave the good jdbc URL you should see

![image](https://cloud.githubusercontent.com/assets/1119660/19076030/86572d68-8a47-11e6-8625-c98eb7d225e1.png)

**Comment by gedOHub** [comment]
Thank you. It works
