### ISSUE TITLE
Compatibility GitBucket 4.20.0

### ISSUE THREAD

**Issue by dermig** [gitbucket/gitbucket-h2-backup-plugin#26]
The plugin seems to be incompatible with GitBucket Version 4.20.0 (it's not loaded).

**Comment by rockccf** [comment]
I'm using the gitbucket version 4.21.2 and I got the following error.
Error during plugin initialization: gitbucket-h2-backup-plugin_2.12-1.6.0.jar
java.lang.IllegalStateException: Plugin version is 1.6.0, but database version is 1.0

**Comment by aadrian** [comment]
@rockccf you have to manually edit the Versions table since it contains the "1.0" values. For whatever reason, GitBucket was not able to update it to "1.6.0", so you have to manually edit that value: only after that the plug-in will work.

**Comment by rockccf** [comment]
@aadrian Thanks. It works now.
