### ISSUE TITLE
What version of GitBucket is this plug-in compatible with?

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket-h2-backup-plugin#7]
What version of GitBucket is this plug-in compatible with?
The Gist plug-in https://github.com/gitbucket/gitbucket-gist-plugin
clearly lists the version mapping.

It would be very helpful if all plug-ins would follow this.

Thanks in advance.

**Comment by McFoggy** [comment]
You're right @aadrian this would be a cool addition.

I'd find interresting also that at runtime the plugins list the version of gitbucket against which they have been tested. This will require some additions inside gitbucket itself. Can you open an issue there to report such a requirement please?

**Comment by McFoggy** [comment]
Until gitbucket-core provides something better I added a compatibility table in the [README](/gitbucket-plugins/gitbucket-h2-backup-plugin)
